# https://www.archlinux.org/groups/x86_64/gnome-extra/
GNOME_APPS=
# GNOME_APPS="$GNOME_APPS accerciser"                 # Interactive Python accessibility explorer for the GNOME desktop 	2016-10-12
# GNOME_APPS="$GNOME_APPS aisleriot"                  # A collection of patience games written in guile scheme 	2016-11-07
# GNOME_APPS="$GNOME_APPS anjuta"                     # GNOME Integrated Development Environment (IDE) 	2016-10-12
# GNOME_APPS="$GNOME_APPS atomix"                     # Build molecules out of single atoms 	2016-10-12
# GNOME_APPS="$GNOME_APPS brasero"                    # CD/DVD mastering tool 	2016-07-28
# GNOME_APPS="$GNOME_APPS cheese"                     # Take photos and videos with your webcam, with fun graphical effects 	2016-10-12
# GNOME_APPS="$GNOME_APPS devhelp"                    # API documentation browser for GNOME 	2016-10-12
# GNOME_APPS="$GNOME_APPS evolution"                  # Manage your email, contacts and schedule 	2016-11-07
# GNOME_APPS="$GNOME_APPS file-roller"                # Create and modify archives 	2016-11-08
# GNOME_APPS="$GNOME_APPS five-or-more"               # Remove colored balls from the board by forming lines 	2016-11-08
# GNOME_APPS="$GNOME_APPS four-in-a-row"              # Make lines of the same color to win 	2016-11-08
GNOME_APPS="$GNOME_APPS gedit"                      # A text editor for GNOME 	2016-10-12
GNOME_APPS="$GNOME_APPS gedit-code-assistance"      # Code assistance for gedit 	2016-11-12
GNOME_APPS="$GNOME_APPS gitg"                       # A GIT repository viewer based on GTK+ 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-2048"                 # Obtain the 2048 tile 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-builder"              # An IDE for writing GNOME-based software 	2016-11-02
# GNOME_APPS="$GNOME_APPS gnome-calendar"             # Simple and beautiful calendar application designed to perfectly fit the GNOME desktop 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-characters"           # A character map application 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-chess"                # Play the classic two-player boardgame of chess 	2016-11-07
# GNOME_APPS="$GNOME_APPS gnome-clocks"               # Clocks applications for GNOME 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-code-assistance"      # Code assistance services for GNOME 	2016-07-28
# GNOME_APPS="$GNOME_APPS gnome-color-manager"        # GNOME Color Profile Tools 	2016-11-07
# GNOME_APPS="$GNOME_APPS gnome-devel-docs"           # Developer documentation for GNOME 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-documents"            # A document manager application for GNOME 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-getting-started-docs" # Help a new user get started in GNOME 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-klotski"              # Slide blocks to solve the puzzle 	2016-11-08
# GNOME_APPS="$GNOME_APPS gnome-logs"                 # A log viewer for the systemd journal 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-mahjongg"             # Disassemble a pile of tiles by removing matching pairs 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-maps"                 # A simple GNOME 3 maps application 	2016-11-07
# GNOME_APPS="$GNOME_APPS gnome-mines"                # Clear hidden mines from a minefield 	2016-11-08
# GNOME_APPS="$GNOME_APPS gnome-music"                # Music player and management application 	2016-11-09
# GNOME_APPS="$GNOME_APPS gnome-nettool"              # Graphical interface for various networking tools 	2016-07-28
# GNOME_APPS="$GNOME_APPS gnome-nibbles"              # Guide a worm around a maze 	2016-11-09
# GNOME_APPS="$GNOME_APPS gnome-photos"               # Access, organize, and share your photos on GNOME 	2016-11-07
# GNOME_APPS="$GNOME_APPS gnome-robots"               # Avoid the robots and make them crash into each other 	2016-11-08
# GNOME_APPS="$GNOME_APPS gnome-sound-recorder"       # A utility to make simple audio recording from your GNOME desktop 	2016-05-09
# GNOME_APPS="$GNOME_APPS gnome-sudoku"               # Test your logic skills in this number grid puzzle 	2016-11-07
# GNOME_APPS="$GNOME_APPS gnome-taquin"               # Move tiles so that they reach their places 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-tetravex"             # Complete the puzzle by matching numbered tiles 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-todo"                 # Task manager for GNOME 	2016-11-01
# GNOME_APPS="$GNOME_APPS gnome-tweak-tool"           # Customize advanced GNOME 3 options 	2016-10-12
# GNOME_APPS="$GNOME_APPS gnome-weather"              # Access current weather conditions and forecasts 	2016-08-16
# GNOME_APPS="$GNOME_APPS hitori"                     # GTK+ application to generate and let you play games of Hitori 	2016-10-12
# GNOME_APPS="$GNOME_APPS iagno"                      # Dominate the board in a classic version of Reversi 	2016-10-12
# GNOME_APPS="$GNOME_APPS libgnome-games-support"     # Code shared between GNOME games 	2016-10-12
# GNOME_APPS="$GNOME_APPS lightsoff"                  # Turn off all the lights 	2016-11-08
# GNOME_APPS="$GNOME_APPS nautilus-sendto"            # Easily send files via mail 	2016-07-28
# GNOME_APPS="$GNOME_APPS orca"                       # Screen reader for individuals who are blind or visually impaired 	2016-11-08
# GNOME_APPS="$GNOME_APPS polari"                     # An IRC Client for GNOME 	2016-11-10
# GNOME_APPS="$GNOME_APPS quadrapassel"               # Fit falling blocks together (Tetris-like game for GNOME) 	2016-10-12
# GNOME_APPS="$GNOME_APPS rygel"                      # UPnP AV MediaServer and MediaRenderer that allows you to easily share audio, video and pictures, and control of media player on your home network 	2016-10-12
# GNOME_APPS="$GNOME_APPS seahorse"                   # GNOME application for managing PGP keys. 	2016-10-12
# GNOME_APPS="$GNOME_APPS swell-foop"                 # Clear the screen by removing groups of colored and shaped tiles 	2016-11-08
# GNOME_APPS="$GNOME_APPS tali"                       # Beat the odds in a poker-style dice game 	2016-10-12
# GNOME_APPS="$GNOME_APPS vinagre"                    # A VNC Client for the GNOME desktop 	2016-10-12

echo_section "Installing GNOME applications"
ensure_pkg $GNOME_APPS
