KDE_APPS=
# KDE_APPS="$KDE_APPS akonadiconsole"                     # Akonadi Management and Debugging Console
# KDE_APPS="$KDE_APPS akregator"                          # A Feed Reader for KDE
# KDE_APPS="$KDE_APPS ark"                                # Archiving Tool
# KDE_APPS="$KDE_APPS artikulate"                         # Improve your pronunciation by listening to native speakers
# KDE_APPS="$KDE_APPS blinken"                            # Memory Enhancement Game
# KDE_APPS="$KDE_APPS blogilo"                            # A KDE Blogging Client
# KDE_APPS="$KDE_APPS bomber"                             # A single player arcade game
# KDE_APPS="$KDE_APPS bovo"                               # A Gomoku like game for two players
# KDE_APPS="$KDE_APPS cantor"                             # KDE Frontend to Mathematical Software
# KDE_APPS="$KDE_APPS cervisia"                           # CVS Frontend
KDE_APPS="$KDE_APPS dolphin"                            # File Manager
KDE_APPS="$KDE_APPS dolphin-plugins"                    # Extra Dolphin plugins
# KDE_APPS="$KDE_APPS dragon"                             # A multimedia player where the focus is on simplicity, instead of features
# KDE_APPS="$KDE_APPS ffmpegthumbs"                       # FFmpeg-based thumbnail creator for video files
# KDE_APPS="$KDE_APPS filelight"                          # View disk usage information
# KDE_APPS="$KDE_APPS granatier"                          # A clone of the classic Bomberman game
KDE_APPS="$KDE_APPS gwenview"                           # A fast and easy to use image viewer for KDE
# KDE_APPS="$KDE_APPS kaccounts-integration"              # Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
# KDE_APPS="$KDE_APPS kaccounts-providers"                # Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
# KDE_APPS="$KDE_APPS kaddressbook"                       # Contact Manager
# KDE_APPS="$KDE_APPS kalarm"                             # Personal Alarm Scheduler
# KDE_APPS="$KDE_APPS kalgebra"                           # Graph Calculator
# KDE_APPS="$KDE_APPS kamera"                             # KDE integration for gphoto2 cameras
# KDE_APPS="$KDE_APPS kanagram"                           # Letter Order Game
# KDE_APPS="$KDE_APPS kapman"                             # A clone of the well known game Pac-Man
# KDE_APPS="$KDE_APPS kapptemplate"                       # KDE Template Generator
KDE_APPS="$KDE_APPS kate"                               # Advanced Text Editor
# KDE_APPS="$KDE_APPS katomic"                            # A fun and educational game built around molecular geometry
# KDE_APPS="$KDE_APPS kblackbox"                          # A game of hide and seek played on a grid of boxes
# KDE_APPS="$KDE_APPS kblocks"                            # The classic falling blocks game
# KDE_APPS="$KDE_APPS kbounce"                            # A single player arcade game with the elements of puzzle
# KDE_APPS="$KDE_APPS kbreakout"                          # A Breakout-like game
# KDE_APPS="$KDE_APPS kbruch"                             # Exercise Fractions
KDE_APPS="$KDE_APPS kcalc"                              # Scientific Calculator
KDE_APPS="$KDE_APPS kcharselect"                        # Character Selector
KDE_APPS="$KDE_APPS kcolorchooser"                      # Color Chooser
KDE_APPS="$KDE_APPS kcron"                              # Configure and schedule tasks
# KDE_APPS="$KDE_APPS kde-dev-scripts"                    # Scripts and setting files useful during development of KDE software
# KDE_APPS="$KDE_APPS kdeaccessibility-jovie"             # A text to speech application
# KDE_APPS="$KDE_APPS kdeaccessibility-kaccessible"       # Provides accessibility services like focus tracking and a screenreader
# KDE_APPS="$KDE_APPS kdeaccessibility-kmag"              # Screen Magnifier
# KDE_APPS="$KDE_APPS kdeaccessibility-kmousetool"        # Clicks the mouse for you, reducing the effects of RSI
# KDE_APPS="$KDE_APPS kdeaccessibility-kmouth"            # Speech Synthesizer Frontend
KDE_APPS="$KDE_APPS kdeadmin-kuser"                     # User Manager
KDE_APPS="$KDE_APPS kdebase-kdepasswd"                  # Change Password
KDE_APPS="$KDE_APPS kdebase-kdialog"                    # A utility for displaying dialog boxes from shell scripts
# KDE_APPS="$KDE_APPS kdebase-keditbookmarks"             # Bookmark Organizer and Editor
KDE_APPS="$KDE_APPS kdebase-kfind"                      # Find Files/Folders
# KDE_APPS="$KDE_APPS kdebase-konq-plugins"               # Extra plugins for Konqueror
# KDE_APPS="$KDE_APPS kdebase-konqueror"                  # KDE File Manager & Web Browser
# KDE_APPS="$KDE_APPS kdebugsettings"                     # An application to enable/disable qCDebug
# KDE_APPS="$KDE_APPS kdeedu-kalzium"                     # Periodic Table of Elements
# KDE_APPS="$KDE_APPS kdeedu-ktouch"                      # Touch Typing Tutor
# KDE_APPS="$KDE_APPS kdegames-kajongg"                   # The ancient Chinese board game for 4 players
# KDE_APPS="$KDE_APPS kdegames-kgoldrunner"               # A game of action and puzzle solving
# KDE_APPS="$KDE_APPS kdegames-kigo"                      # An open-source implementation of the popular Go game
# KDE_APPS="$KDE_APPS kdegames-kolf"                      # A miniature golf game with 2d top-down view
# KDE_APPS="$KDE_APPS kdegames-konquest"                  # The KDE version of Gnu-Lactic
# KDE_APPS="$KDE_APPS kdegames-kreversi"                  # A simple one player strategy game played against the computer
# KDE_APPS="$KDE_APPS kdegames-ksirk"                     # A computerized version of a well known strategy game
# KDE_APPS="$KDE_APPS kdegames-ksnakeduel"                # A simple snake duel game
# KDE_APPS="$KDE_APPS kdegames-kspaceduel"                # Each of two possible players controls a satellite spaceship orbiting the sun
# KDE_APPS="$KDE_APPS kdegames-ksudoku"                   # A logic-based symbol placement puzzle
# KDE_APPS="$KDE_APPS kdegames-kubrick"                   # Based on the famous Rubik's Cube
# KDE_APPS="$KDE_APPS kdegames-lskat"                     # Lieutenant Skat is a fun and engaging card game for two players
# KDE_APPS="$KDE_APPS kdegames-palapeli"                  # A single-player jigsaw puzzle game
# KDE_APPS="$KDE_APPS kdegraphics-mobipocket"             # A collection of plugins to handle mobipocket files
# KDE_APPS="$KDE_APPS kdegraphics-okular"                 # Document Viewer
# KDE_APPS="$KDE_APPS kdemultimedia-audiocd-kio"          # Kioslave for accessing audio CDs
# KDE_APPS="$KDE_APPS kdemultimedia-juk"                  # A jukebox, tagger and music collection manager
# KDE_APPS="$KDE_APPS kdemultimedia-kmix"                 # KDE volume control program
# KDE_APPS="$KDE_APPS kdemultimedia-kscd"                 # KDE CD player
# KDE_APPS="$KDE_APPS kdenetwork-filesharing"             # Properties dialog plugin to share a directory with the local network
# KDE_APPS="$KDE_APPS kdenetwork-kget"                    # Download Manager
# KDE_APPS="$KDE_APPS kdenetwork-kopete"                  # Instant Messenger
# KDE_APPS="$KDE_APPS kdenetwork-kopete"                  # Instant Messenger
# KDE_APPS="$KDE_APPS kdenetwork-kppp"                    # Internet Dial-Up Tool
# KDE_APPS="$KDE_APPS kdenetwork-zeroconf-ioslave"        # Network Monitor for DNS-SD services (Zeroconf)
# KDE_APPS="$KDE_APPS kdenlive"                           # A non-linear video editor for Linux using the MLT video framework
# KDE_APPS="$KDE_APPS kdepim-addons"                      # Addons for KDE PIM applications
# KDE_APPS="$KDE_APPS kdesdk-dev-utils"                   # Small utilities for developers using KDE/Qt libs/frameworks
# KDE_APPS="$KDE_APPS kdesdk-kcachegrind"                 # Visualization of Performance Profiling Data
# KDE_APPS="$KDE_APPS kdesdk-thumbnailers"                # Plugins for the thumbnailing system
# KDE_APPS="$KDE_APPS kdeutils-kgpg"                      # A GnuPG frontend
# KDE_APPS="$KDE_APPS kdeutils-kremotecontrol"            # Configure your remote controls for use with applications
# KDE_APPS="$KDE_APPS kdeutils-sweeper"                   # System Cleaner
# KDE_APPS="$KDE_APPS kdewebdev-kfilereplace"             # Search & Replace Tool
# KDE_APPS="$KDE_APPS kdewebdev-kimagemapeditor"          # HTML Image Map Editor
# KDE_APPS="$KDE_APPS kdewebdev-klinkstatus"              # Link Checker
# KDE_APPS="$KDE_APPS kdewebdev-kommander"                # Executor for Kommander dialogs
# KDE_APPS="$KDE_APPS kdf"                                # View Disk Usage
# KDE_APPS="$KDE_APPS kdiamond"                           # A single player puzzle game
# KDE_APPS="$KDE_APPS kfloppy"                            # Floppy Formatter
# KDE_APPS="$KDE_APPS kfourinline"                        # A four-in-a-row game
# KDE_APPS="$KDE_APPS kgeography"                         # Geography Trainer
# KDE_APPS="$KDE_APPS khangman"                           # Hangman Game
# KDE_APPS="$KDE_APPS khelpcenter"                        # Application to show KDE Applications' documentation
# KDE_APPS="$KDE_APPS kig"                                # Interactive Geometry
# KDE_APPS="$KDE_APPS killbots"                           # A simple game of evading killer robots
# KDE_APPS="$KDE_APPS kio-extras"                         # Additional components to increase the functionality of KIO
# KDE_APPS="$KDE_APPS kiriki"                             # An addictive and fun dice game
# KDE_APPS="$KDE_APPS kiten"                              # Japanese Reference/Study Tool
# KDE_APPS="$KDE_APPS kjumpingcube"                       # A simple tactical game
# KDE_APPS="$KDE_APPS kleopatra"                          # Certificate Manager and Unified Crypto GUI
# KDE_APPS="$KDE_APPS klettres"                           # Learn The Alphabet
# KDE_APPS="$KDE_APPS klickety"                           # An adaptation of the Clickomania game
# KDE_APPS="$KDE_APPS klines"                             # A simple but highly addictive, one player game
# KDE_APPS="$KDE_APPS kmahjongg"                          # A tile matching game for one or two players
# KDE_APPS="$KDE_APPS kmail"                              # Mail Client
# KDE_APPS="$KDE_APPS kmines"                             # The classic Minesweeper game
# KDE_APPS="$KDE_APPS kmplot"                             # Mathematical Function Plotter
# KDE_APPS="$KDE_APPS knavalbattle"                       # A ship sinking game
# KDE_APPS="$KDE_APPS knetwalk"                           # Connect all the terminals to the server, in as few turns as possible
# KDE_APPS="$KDE_APPS knotes"                             # Popup Notes
# KDE_APPS="$KDE_APPS kollision"                          # A simple ball dodging game
# KDE_APPS="$KDE_APPS kolourpaint"                        # Paint Program
# KDE_APPS="$KDE_APPS kompare"                            # Diff/Patch Frontend
KDE_APPS="$KDE_APPS konsole"                            # Terminal
# KDE_APPS="$KDE_APPS konsolekalendar"                    # Command line tool for accessing calendar files
# KDE_APPS="$KDE_APPS kontact"                            # Personal Information Manager
# KDE_APPS="$KDE_APPS korganizer"                         # Calendar and Scheduling Program
# KDE_APPS="$KDE_APPS kpatience"                          # Offers a selection of solitaire card games
# KDE_APPS="$KDE_APPS krdc"                               # Remote Desktop Client
# KDE_APPS="$KDE_APPS krfb"                               # Desktop Sharing
# KDE_APPS="$KDE_APPS kross-interpreters"                 # Language interpreters to enable in-process scripting with Kross
# KDE_APPS="$KDE_APPS kruler"                             # Screen Ruler
# KDE_APPS="$KDE_APPS kshisen"                            # A solitaire-like game played using the standard set of Mahjong tiles
# KDE_APPS="$KDE_APPS ksquares"                           # A modeled after the well known pen and paper based game of Dots and Boxes
# KDE_APPS="$KDE_APPS kstars"                             # Desktop Planetarium
# KDE_APPS="$KDE_APPS ksystemlog"                         # System log viewer tool
# KDE_APPS="$KDE_APPS kteatime"                           # Tea Cooker
# KDE_APPS="$KDE_APPS ktimer"                             # Countdown Launcher
# KDE_APPS="$KDE_APPS ktnef"                              # A viewer/extractor for TNEF files
# KDE_APPS="$KDE_APPS ktuberling"                         # A simple constructor game suitable for children and adults alike
# KDE_APPS="$KDE_APPS kturtle"                            # Educational Programming Environment
# KDE_APPS="$KDE_APPS kwalletmanager"                     # Wallet management tool
# KDE_APPS="$KDE_APPS kwordquiz"                          # Flash Card Trainer
# KDE_APPS="$KDE_APPS kwrite"                             # Text Editor
# KDE_APPS="$KDE_APPS lokalize"                           # Computer-Aided Translation System
# KDE_APPS="$KDE_APPS marble"                             # Desktop Globe
# KDE_APPS="$KDE_APPS minuet"                             # A KDE Software for Music Education
# KDE_APPS="$KDE_APPS okteta"                             # Hex Editor
# KDE_APPS="$KDE_APPS parley"                             # Vocabulary Trainer
# KDE_APPS="$KDE_APPS picmi"                              # A nonogram logic game for KDE
# KDE_APPS="$KDE_APPS poxml"                              # Translates DocBook XML files using gettext po files
# KDE_APPS="$KDE_APPS print-manager"                      # A tool for managing print jobs and printers
# KDE_APPS="$KDE_APPS rocs"                               # Graph Theory IDE
# KDE_APPS="$KDE_APPS signon-kwallet-extension"           # KWallet signon extension
# KDE_APPS="$KDE_APPS spectacle"                          # KDE screenshot capture utility
# KDE_APPS="$KDE_APPS step"                               # Interactive Physical Simulator
# KDE_APPS="$KDE_APPS telepathy-kde-accounts-kcm"         # KCM Module for configuring Telepathy Instant Messaging Accounts
# KDE_APPS="$KDE_APPS telepathy-kde-approver"             # KDE Channel Approver for Telepathy
# KDE_APPS="$KDE_APPS telepathy-kde-auth-handler"         # Provide UI/KWallet Integration For Passwords and SSL Errors on Account Connect
# KDE_APPS="$KDE_APPS telepathy-kde-call-ui"              # Voice/Video Call UI for Telepathy
# KDE_APPS="$KDE_APPS telepathy-kde-common-internals"     # Common components for KDE-Telepathy
# KDE_APPS="$KDE_APPS telepathy-kde-contact-list"         # KDE Telepathy contact list application
# KDE_APPS="$KDE_APPS telepathy-kde-contact-runner"       # KRunner plugin for KDE Telepathy
# KDE_APPS="$KDE_APPS telepathy-kde-desktop-applets"      # The KDE-Telepathy Plasma desktop applets
# KDE_APPS="$KDE_APPS telepathy-kde-filetransfer-handler" # KDE Telepathy file transfer handler
# KDE_APPS="$KDE_APPS telepathy-kde-integration-module"   # Sits in KDED and takes care of various bits of system integration like setting user to auto-away or handling connection errors
# KDE_APPS="$KDE_APPS telepathy-kde-send-file"            # A File manager plugin to launch a file transfer job with a specified contact
# KDE_APPS="$KDE_APPS telepathy-kde-text-ui"              # Telepathy handler for Text Chats
# KDE_APPS="$KDE_APPS umbrello"                           # UML modeller

echo_section "Installing KDE applications"
ensure_pkg $KDE_APPS
