#### 1_linux ####

# Network
INSTALL_NETWORK_MANAGER=true

USE_SYSTEMD_NETWORKD=false
# The following Network settings are for use with systemd-networkd only

NETWORK_WIRED_DEVICE=$(networkctl | awk '/ether/ {print $2}')
NETWORK_WIRELESS_DEVICE=$(networkctl | awk '/wlan/ {print $2}')

NETWORK_WIRED_DHCP=true
# If DHCP=false:
NETWORK_WIRED_FIXED_ADDRESS="192.168.0.2/24"
NETWORK_WIRED_FIXED_DNS="192.168.0.1"
NETWORK_WIRED_FIXED_GATEWAY="192.168.0.1"

NETWORK_WIRELESS_DHCP=true
# If DHCP=false:
NETWORK_WIRELESS_FIXED_ADDRESS="192.168.0.3/24"
NETWORK_WIRELESS_FIXED_DNS="192.168.0.1"
NETWORK_WIRELESS_FIXED_GATEWAY="192.168.0.1"

NETWORK_WIRELESS_ESSID="MyNetwork"
prompt_passwd "Wireless network" "${NETWORK_WIRELESS_ESSID}"
NETWORK_WIRELESS_passphrase=${PROMPT_PASSWD}


# Video drivers
INSTALL_NVIDIA_CUDA=true

# Audio
AUDIO_DEVICE=
# AUDIO_DEVICE="hw:1,7"

# Git
GIT_USER_NAME="My Name"
GIT_USER_EMAIL="myname@email.com"
GIT_GLOBAL_PUSH_DEFAULT="simple"


#### 2_www ####

# OpenSSH
OPENSSH_SERVER_PORT=22
OPENSSH_SERVER_PASSWORD_AUTHENTICATION=false

# nginx
NGINX_DOMAIN_NAME="$OS_HOSTNAME"
NGINX_SSL_O="My Organisation"
NGINX_SSL_OU="Unit"
NGINX_SSL_CN=${NGINX_DOMAIN_NAME}

# Apache
APACHE_DOMAIN_NAME=${NGINX_DOMAIN_NAME}
APACHE_PORT=8080
APACHE_SERVER_ADMIN=you@example.com



#### 3_db ####

# MariaDB
prompt_passwd "MariaDB" "root"
MARIADB_ROOT_PASSWORD=${PROMPT_PASSWD}
MARIADB_REMOVE_ANONYMOUS_USERS="y"
MARIADB_DISALLOW_REMOTE_ROOT_LOGIN="y"
MARIADB_REMOVE_TEST_DB="n"
MARIADB_RELOAD_PRIVILEGE_TABLES="y"



#### 5_server ####

# Nextcloud
NEXTCLOUD_ncpath='/usr/share/webapps/nextcloud'
NEXTCLOUD_ncpath_DATA="data"
NEXTCLOUD_ncpath_ASSETS="assets"
NEXTCLOUD_htuser='http'
NEXTCLOUD_htgroup='http'
NEXTCLOUD_rootuser='root'
NEXTCLOUD_nc_admin_user='admin'
prompt_passwd "Nextcloud" "${NEXTCLOUD_nc_admin_user}"
NEXTCLOUD_nc_admin_pass=${PROMPT_PASSWD}

NEXTCLOUD_BACKUP_DIR=${DATA_PARTITION_MOUNT_FOLDER}/.backups/nextcloud
NEXTCLOUD_RESTORE_BACKUP_IF_AVAILABLE="true"
NEXTCLOUD_CREATE_BACKUP_IF_MISSING="true"

# VLC
VLC_HTTP_PORT=8090
prompt_passwd "VLC" "web service"
VLC_HTTP_PASSWORD=${PROMPT_PASSWD}



#### 6_workstation ####

# xorg
XORG_SET_SCREEN_RESOLUTION=false
XORG_ADD_SCREEN_RESOLUTION=false
XORG_ADD_SCREEN_RESOLUTION_WIDTH=1280
XORG_ADD_SCREEN_RESOLUTION_HEIGHT=1024
XORG_ADD_SCREEN_RESOLUTION_DRIVER=intel

# KDE
KDE_ALL_APPLICATIONS=true

# GNOME
GNOME_ALL_APPLICATIONS=true



PROMPT_PASSWD=
